[package]
name = "add6"
version = "0.1.0"
authors = ["Felix S. Klock II <pnkfelix@pnkfx.org>"]
description = "Toy crate that depends on past version of add3 crate."
license = "Unlicense"

[dependencies]
add3 = "1.0.0"
