[package]
name = "add6_64b"
version = "0.1.0"
authors = ["Felix S. Klock II <pnkfelix@pnkfx.org>"]
description = "Toy crate that depends on recent version of add3 crate."
license = "Unlicense"
repository = "https://github.com/pnkfelix/add3/tree/add6_64b"

[dependencies]
add3 = "4.0.0"
