[package]
name = "add3"
version = "2.0.1"
authors = ["Felix S. Klock II <pnkfelix@pnkfx.org>"]
description = "Toy crate that will go through major version changes to demo semver."
repository = "https://github.com/pnkfelix/add3"
license = "Unlicense"
